sudo: enabled
dist: trusty
language: generic

branches:
  only:
    - master
git:
  submodules: false

# env:
#   - TARGET=${HOME}/build/3 BASE=7.0.1.1 REQUIRE=3.0.0  BUILDING_MOD=ca

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9" TARGET=${HOME}/build/1 BASE=3.15.5  REQUIRE=3.0.0  BUILDING_MOD=ctia4
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9" TARGET=${HOME}/build/2 BASE=3.15.5  REQUIRE=3.0.2  BUILDING_MOD=ctia4
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9" TARGET=${HOME}/build/3 BASE=7.0.1.1 REQUIRE=3.0.0  BUILDING_MOD=ctia
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9" TARGET=${HOME}/build/4 BASE=7.0.1.1 REQUIRE=3.0.2  BUILDING_MOD=ctia

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5" TARGET=${HOME}/build/1 BASE=3.15.5  REQUIRE=3.0.0  BUILDING_MOD=ctia4
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5" TARGET=${HOME}/build/2 BASE=3.15.5  REQUIRE=3.0.2  BUILDING_MOD=ctia4
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5" TARGET=${HOME}/build/3 BASE=7.0.1.1 REQUIRE=3.0.0  BUILDING_MOD=ctia
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5" TARGET=${HOME}/build/4 BASE=7.0.1.1 REQUIRE=3.0.2  BUILDING_MOD=ctia

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6" TARGET=${HOME}/build/1 BASE=3.15.5  REQUIRE=3.0.0  BUILDING_MOD=ctia4
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6" TARGET=${HOME}/build/2 BASE=3.15.5  REQUIRE=3.0.2  BUILDING_MOD=ctia4
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6" TARGET=${HOME}/build/3 BASE=7.0.1.1 REQUIRE=3.0.0  BUILDING_MOD=ctia
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6" TARGET=${HOME}/build/4 BASE=7.0.1.1 REQUIRE=3.0.2  BUILDING_MOD=ctia

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7" TARGET=${HOME}/build/1 BASE=3.15.5  REQUIRE=3.0.0  BUILDING_MOD=ctia4
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7" TARGET=${HOME}/build/2 BASE=3.15.5  REQUIRE=3.0.2  BUILDING_MOD=ctia4
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7" TARGET=${HOME}/build/3 BASE=7.0.1.1 REQUIRE=3.0.0  BUILDING_MOD=ctia
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7" TARGET=${HOME}/build/4 BASE=7.0.1.1 REQUIRE=3.0.2  BUILDING_MOD=ctia
   

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get -qq update
  - sudo apt-get install -y realpath ipmitool libtool automake re2c tclx build-essential libreadline-dev libxt-dev x11proto-print-dev libxmu-headers libxmu-dev libxmu6 libxpm-dev libxmuu-dev libxmuu1 libpcre++-dev libsnmp-dev re2c darcs python-dev libnetcdf-dev libhdf5-dev libpng-dev libbz2-dev libxml2-dev libusb-dev libusb-1.0-0-dev libudev-dev tree 
  - cp -r $TRAVIS_BUILD_DIR ${TARGET}
  - cd ${TARGET}
  - echo ${PWD}

install:
  - bash e3_building_test.bash -t ${TARGET}/.epics -b ${BASE} -r ${REQUIRE}

script:
  - bash e3.bash -${BUILDING_MOD} all2

after_successfter_sucesst:
  - source ${TARGET}/.epics/base-${BASE}/require/${REQUIRE}/bin/setE3Env.bash
  - bash e3.bash -${BUILDING_MOD} cmd
  - cat .cmd
  - iocsh.bash .cmd > ${TARGET}/.output&
  - pid=$!
  - cat ${TARGET}/.output
  - kill -9 $pid
  - rm ${TARGET}/.output
 