sudo: required
dist: trusty
language: generic

git:
    submodules: false
    
before_install:
  - bash -c 'echo $BASH_VERSION'
  - sudo apt-get -qq update
  - sudo apt-get install -y screen nano unzip tree ipmitool libtool automake re2c tclx realpath aptitude
  - sudo aptitude install -y build-essential libreadline-dev
  - ./.ci/build.bash