sudo: enabled

dist: trusty

language: generic

branches:
  only:
    - master

git:
  submodules: false
  
  
env:
  global:
    - E3_PATH=${TRAVIS_BUILD_DIR}/epics
  matrix:
    - SESSION=1 BASE=3.15.5  TAG=3.15.5      REQUIRE=3.0.0  BUILDING_MOD=ctiea4l
    - SESSION=2 BASE=3.15.5  TAG=3.15.5      REQUIRE=3.0.2  BUILDING_MOD=ctiea4l
#   - SESSION=3 BASE=3.15.6  TAG=3.15.6-rc1  REQUIRE=3.0.0  BUILDING_MOD=ctiea4l
    - SESSION=4 BASE=3.15.6  TAG=3.15.6-rc1  REQUIRE=3.0.2  BUILDING_MOD=ctiea4l
#   - SESSION=5 BASE=7.0.1.1 TAG=7.0.1.1     REQUIRE=3.0.0  BUILDING_MOD=ctieaol
    - SESSION=6 BASE=7.0.1.1 TAG=7.0.1.1     REQUIRE=3.0.2  BUILDING_MOD=ctieaol
#  - SESSION=4 BASE=7.0.1.1  REQUIRE=3.0.2  BUILDING_MOD=cao
  
before_install:
  - sudo apt-get -qq update > /dev/null 2>&1
  - sudo apt-get install -y linux-headers-$(uname -r)  > /dev/null 2>&1
  - sudo apt-get install -y build-essential realpath ipmitool libtool automake tclx  tree screen re2c darcs > /dev/null 2>&1
  - sudo apt-get install -y libreadline-dev libxt-dev x11proto-print-dev libxmu-headers libxmu-dev libxpm-dev libxmuu-dev libxmuu1 libpcre++-dev libsnmp-dev python-dev libnetcdf-dev libhdf5-dev libpng-dev libbz2-dev libxml2-dev libusb-dev libusb-1.0-0-dev libudev-dev libraw1394-dev libboost-dev libboost-regex-dev libboost-filesystem-dev  > /dev/null 2>&1
  - bash .ci/before_install_conf.bash
  - bash e3_building_test.bash -t "${E3_PATH}" -b "${BASE}" -r "${REQUIRE}" -c "${TAG}"

install:
  - bash e3.bash -${BUILDING_MOD} call  > /dev/null 2>&1
  - bash e3.bash -${BUILDING_MOD} gall  > /dev/null 2>&1
  - bash e3.bash -${BUILDING_MOD} i2all
  - bash e3.bash -${BUILDING_MOD} bbase 
  - bash e3.bash -${BUILDING_MOD} breq 
  - bash e3.bash -${BUILDING_MOD} bmod

after_success:
  - bash e3.bash -${BUILDING_MOD} cmd
  - source ${E3_PATH}/base-${BASE}/require/${REQUIRE}/bin/setE3Env.bash
  - bash .ci/screen.bash ${SESSION} .cmd


  
 
